apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier-app
  labels:
    app: frontend
    tier: presentation

spec:
  replicas: 2
  selector:
    matchLabels:
      labels:
        app: frontend
        tier: presentation
  template:
    metadata:
      labels:
        app: frontend
        tier: presentation
    
    spec:
      containers:
      - naame: frontend
        image: rattisyam/three-tier-frontend:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
          protocol: TCP

        env:
        - name: REACT_APP_API_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: REACT_APP_API_URL

        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3



---
apiVersion: v1
kind: Service
metadata:
  namespace: three-tier-app
  name: frontend-service
  labels:
    app: frontend
    tier: presentation
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  type: ClusterIP

  # For cloud providers (AWS/GCP/Azure), this will provision a load balancer
  # For local development (Minikube/Kind), use NodePort or port-forward instead
  
    


        
      