apiVersion: v1
kind: persistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: notes-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard